### ISSUE TITLE
Reproducible test_dataset crash on Windows / 1.10.2 from anaconda

### ISSUE THREAD

**Issue by aldanor** [aldanor/hdf5-rust#104]
https://github.com/aldanor/hdf5-rust/runs/924910831

Anyone who has a windows box is welcome to check this out ^

Seems to results in `STATUS_HEAP_CORRUPTION` in `test_dataset`.

**Comment by aldanor** [comment]
@magnusuMET ^ btw: this will be a blocker for migrating everything fully to GHA and releasing a new version, I think.

There's another reproducible macOS test failure on 1.8.18 with homebrew build, but that one I'll take on myself since I have a mac box at home.

**Comment by magnusuMET** [comment]
I can reproduce on a virtual machine running on linux. The error occurs in 
`test_read_write_varlen_struct` -> `test_read` -> `assert_eq` (line 113)

The error is probably due to some undefined behaviour. Moving the `?` operator to
```rust
let out_vec = ds.read_raw::<T>()?;
```
makes the assertation pass, but it again fails on the next assertation.

**Comment by aldanor** [comment]
Hm, interesting, needs further investigation.

What we need to figure out, I guess - is it our fault or a known HDF5 bug? If it's the first one causing some UB (although it looks like some very reproducible UB), we have to fix it; if it's a known bug - just skip this test, or maybe try to work around it.

**Comment by aldanor** [comment]
I was thinking also to schedule a weekly run of ~200-250 jobs, running a full test matrix over all known HDF5 versions from all sources on all platforms and all Rust versions - this may help uncover more crash bugs in the future.

(Will probably do it later after this crashbug is investigated and GHA PR is merged in)

**Comment by magnusuMET** [comment]
@aldanor I have a question regarding memory managment of the string types. When reading raw values from a dataset, who has the responsibility for calling `free` on the allocated strings? If it is us, which I assume since the variable strings have a `Drop` implementation, are we sure we are using the same allocator to free as was used to allocate the strings in `hdf5-c`? `STATUS_HEAP_CORRUPTION` looks like an allocator error

**Comment by magnusuMET** [comment]
See https://portal.hdfgroup.org/display/HDF5/H5_FREE_MEMORY,

> It is especially important to use this function to free memory allocated by the library on Windows. The C standard library is implemented in dynamic link libraries (DLLs) known as the C run-time (CRT). Each version of Visual Studio comes with two CRT DLLs (debug and release) and allocating and freeing across DLL boundaries can cause resource leaks and subtle bugs due to heap corruption.
> Only use this function to free memory allocated by the HDF5 Library. It will generally not be safe to use this function to free memory allocated by any other means.
> Even when using this function, it is still best to ensure that all components of a C application are built with the same version of Visual Studio and build (debug or release) and thus linked against the same CRT.

**Comment by magnusuMET** [comment]
All tests does indeed pass when leaking memory instead of calling `libc::free`.

**Comment by aldanor** [comment]
Thanks for investigating!

Yes, it's our job to deallocate it and currently varlen strings in `hdf5-types` use `libc::free` because that crate does not depend on hdf5 crate and may be used without it (that was kind of the point, anyway...).

I remember switching to using `H5free_memory()` in a few places which, IIRC, is guaranteed to deallocate things in a matching fashion, but that's only within hdf crate... https://github.com/aldanor/hdf5-rust/commit/c2cda28b9ba535392870b2ea2311ec5f15520865

**Comment by magnusuMET** [comment]
Should we add `hdf5-sys` as a dependency to `hdf5-types` then? The current situation is a security risk and needs to be fixed.

**Comment by aldanor** [comment]
I don't see how we can access `H5free_memory` from within `hdf5-types` crates, maybe on Windows there's a way to just mismatch between MSVC runtime and the version used to build the library, or something like that?

Also, interesting, why does it happen to fail for that particular version only.

**Comment by magnusuMET** [comment]
I guess it depends on which compiler (and settings) was used for building the library?

**Comment by aldanor** [comment]
> Should we add `hdf5-sys` as a dependency to `hdf5-types` then? The current situation is a security risk and needs to be fixed.

We can, but then you can no longer have downstream apps/crates that use hdf5-compatible memory layouts but don't actually depend on hdf5; that was my main point.

**Comment by aldanor** [comment]
> I guess it depends on which compiler (and settings) was used for building the library?

Yea, we need to figure if it was debug/release and which version; wonder if that's recoverable from the dll somehow? (Btw now I'm even more inclined to do scheduled "crater runs" over huge job matrices)

**Comment by magnusuMET** [comment]
> We can, but then you can no longer have downstream apps/crates that use hdf5-compatible memory layouts but don't actually depend on hdf5; that was my main point.

`crates.io` does not list any dependent crates, and the types must be somewhat tied in with `hdf5` to allow the zero-copy approach. I suppose it is a necessary evil to rely on the `hdf5` allocator.
