### ISSUE TITLE
Add targets to CI

### ISSUE THREAD

**Issue by magnusuMET** [aldanor/hdf5-rust#116]
Official release binaries are now available for all `hdf5` versions, https://forum.hdfgroup.org/t/please-provide-stable-urls-for-official-binaries-without-auth/7378/8.

It would be nice to test this crate with all/some of the releases under https://support.hdfgroup.org/ftp/HDF5/releases/

**Comment by aldanor** [comment]
I know, I was the one to request them :) Yea, was planning to do it. I will also reply to the hdf forum to suggest a bit of renaming for the binaries.

**Comment by magnusuMET** [comment]
I am especially suspicious of how we handle the windows releases, as we have quite a lot of special casing for this platform

**Comment by mulimoen** [comment]
`1.12.0` binaries are tested under windows, which is the most tricky platform (dll...). Any additional targets should be added to #109
