### ISSUE TITLE
Documentation fails to build on docs.rs

### ISSUE THREAD

**Issue by seatonullberg** [aldanor/hdf5-rust#124]
I've noticed that after including this crate as a dependency in my project, docs.rs fails to build the documentation. The build log [here](https://docs.rs/crate/velvet/0.3.0/builds/326695) shows that `hdf5-sys` panicked at:
```
thread 'main' panicked at 'Unable to locate HDF5 root directory and/or headers.', /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/hdf5-sys-0.7.0/build.rs:549:13
```
I checked the build environment packages [here](https://github.com/rust-lang/crates-build-env/blob/master/packages.txt) and it looks like `libhdf5-103` is an included package so I'm confused why `hdf5-sys` fails to build.

**Comment by mulimoen** [comment]
The build on `docs.rs` is actually using a bundled version of `hdf5`. You can have a look at the bottom two lines in `cargo.toml` to see how this is configured

**Comment by seatonullberg** [comment]
Thanks! Adding the metadata to my `Cargo.toml` solved it.
