### ISSUE TITLE
Read variable length attribute string

### ISSUE THREAD

**Issue by geolehmann** [aldanor/hdf5-rust#149]
Hi everybody,

I am stuck with reading attributes from a group and would like tom request some help. See below the entry in HDFview which I want to read:

![hdf5](https://user-images.githubusercontent.com/9590338/117769735-5dff7b80-b234-11eb-9fb7-a1789616537f.png)

I am using pmark´s PR for attribute support which I merged into my fork of hdf5-rust. I can successfully get a list of attributes using the `attr_names` function. Using the code below I was also able to read exactly one attribute value:

`let group = file.group(&link_to_group).unwrap();`
`let attribute = group.attr("Name").unwrap();`
`let attribute_value = attribute.read_scalar::<hdf5::types::VarLenUnicode>().unwrap().as_str();  `
`println!("Name: {}", attribute_value.clone());  `

but then the code hangs and I get a STATUS_HEAP_CORRUPTION error.

Reading the other integer attribute values from the screenshot works without errors.

Can anybody point me in the right direction to fix this? Thanks in advance!

**Comment by mulimoen** [comment]
I've seen this issue on `windows`, and it is related `free` being called on memory that is not owned by the current runtime. Are you linking to a `dll`, what version of `hdf5`? Could you try forcing `h5-alloc` on `hdf5-types`, this would force the string types to go through `H5allocate_memory`/`H5free_memory` in case auto-detection fails.

**Comment by geolehmann** [comment]
Yes, it worked!! After setting the `h5-alloc` feature flag for hdf5-types, the error no longer appears and I can retrieve the attributes properly. Many thanks for the fast help:)

**Comment by mulimoen** [comment]
I'd like to fix this for the future, ideally with a new run on CI. What version of `hdf5` do you use (is it a dll?), and what platform? Ideally this flag should have been set on this combination automatically

**Comment by geolehmann** [comment]
I don´t know if I did everything right in the beginning - I am using the prebuilt binaries from https://www.hdfgroup.org/downloads/hdf5/ - hdf5-1.12.0-Std-win7_64-vs14.zip in my case, since I am using Windows 10. I use the HDF5_DIR and HDF5_ROOT environment variables pointing to the /bin folder of the hdf5 directory.
