### ISSUE TITLE
Silence errors by default, allow unsilencing them?

### ISSUE THREAD

**Issue by aldanor** [aldanor/hdf5-rust#155]
@mulimoen I had this idea for a while now, and most libraries actually do the same:

Errors should be silenced by default, and can be unsilenced purposefuly, e.g. when debugging something. We capture the entire error stack anyway on every error, so there's no need to dump stuff to console at the same time.

(also look at the readme example! would be nice to remove it from there)

**Comment by mulimoen** [comment]
There is tons of functionality regarding errors, we can definitely be a bit smarter about this, e.g.: 
* Extend the error type to grab the error stack on error, and let the user deal with the backtrace (this we partially do already)
* Register a class to handle errors (forward to `log`?)

**Comment by aldanor** [comment]
The first one we kind of already do (although it's very expensive because of the backtrace extraction; so if there's any logic relying on catching errors it will be very slow).

Adding an error handler sounds pretty cool, but you could do it yourself on the outside, no? If you have a `Result<>`, you can choose if you want to forward the error to log or not, yourself?

Whichever the case, I think that *by default* the errors should be silenced, unlike the current default.

**Comment by mulimoen** [comment]
I fully agree errors should be silenced by default, should be easy to hook up the `/dev/zero` handler in `LIBRARY_INIT`. I think a PR focusing on this should addiionally simplify `ErrorStack` a bit, instead of expanding it would be cheaper to pop off the error object (the hid) and expand at a later time.

**Comment by Rikorose** [comment]
@mulimoen in multi-threading scenarios, errors are still shown. This can be also seen e.g. during cargo test as cargo runs the tests in multiple threads.

Is there a way to silence the errors also when using multiple threads to access an hdf5 dataset?

**Comment by mulimoen** [comment]
@Rikorose The current stack is a thread local variable, and the error printer is not set for all error stacks. Could you try calling `sync(||{})` before spawning threads and check if that silences the errors? Could be that we have to check TLS and call `silence_errors` for each thread and not just on the first we encounter

**Comment by Rikorose** [comment]
Does not seem to work. I am using the global rayon thread pool for multi threadding:
```rust
hdf5::sync::sync(|| {});
let mut poolbuilder = rayon::ThreadPoolBuilder::new();
poolbuilder = poolbuilder.start_handler(|_| hdf5::sync::sync(|| {}));
poolbuilder.build_global()?;
```
I am still seeing errors like:
```
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139802791892736:
  #000: ../../../src/H5G.c line 470 in H5Gopen2(): unable to open group
    major: Symbol table
    minor: Can't open object
  #001: ../../../src/H5Gint.c line 318 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: ../../../src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../../src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../../src/H5Gloc.c line 378 in H5G__loc_find_cb(): object '8338192746772258105' doesn't exist
    major: Symbol table
    minor: Object not found
````
