### ISSUE TITLE
Race condition in initialisation

### ISSUE THREAD

**Issue by magnusuMET** [aldanor/hdf5-rust#174]
The following two tests will often cause a hang on `cargo test` when started at the same time
```rust
    #[test]
    fn lock_part1() {
        h5call!(*H5P_ROOT);
    }
    #[test]
    fn lock_part2() {
        *H5P_ROOT;
    }
```

**Comment by aldanor** [comment]
Yep :/ I've noticed the tests hanging as well - I guess that must be it.
