### ISSUE TITLE
pyO3 and HDF5 on windows

### ISSUE THREAD

**Issue by dwerner95** [aldanor/hdf5-rust#195]
Hey All,
Sorry to bother you again!
I am trying to use hdf5-rust for a project with [pyO3](https://github.com/PyO3/pyo3).

While the program works fine on Linux, I am having some trouble on Windows.
Therefore I created a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example#:~:text=In%20computing%2C%20a%20minimal%20working,to%20be%20demonstrated%20and%20reproduced) which is basically the [HDF5 - Pixel example](https://github.com/aldanor/hdf5-rust/blob/master/examples/simple.rs) inside a working pyO3 Python-module.
You can find the whole code [here](https://github.com/dwerner95/pyO3test). 
Note: I can run the Pixel example on windows without issues if i do not use pyO3.

Compiling the code works on both, windows and linux, however execution fails on windows with the following error:
`pyo3_runtime.PanicException: Can not create file: Invalid file access property list id: 720575940379279375`
The same error occurred in #18, however i do not see with this explanation why it should work without Python but fail with it. Maybe I am misinterpreting it.
Can someone help me with this?

**Comment by aldanor** [comment]
Wonder does the readme pixel example work *without* pyo3 on windows in your setup?

**Comment by dwerner95** [comment]
Hey @aldanor,

for whatever reason the plain rust example did run without throwing out an error, however you are right it did not run. The error seemingly occurred due to the same fact as #18.
Changing the HDF5 version from 1.12.1 to 1.10.7 worked for me. 
Thank you both again for this cooperation. you've been really helpful (Even thought the errors where completely on my side.)

**Comment by aldanor** [comment]
@dwerner95 No worries - hope it all works now. Closing this issue for now then. (and #194 leaving open for now due to https://github.com/aldanor/hdf5-rust/issues/194#issuecomment-1021999182)

**Comment by wiwski** [comment]
Hello @dwerner95, I am having the same issue. Downgrading to 1.10.7 did not solve it for me. Did you do something else to make it work ? Thanks !
