### ISSUE TITLE
Specify field names in compound types

### ISSUE THREAD

**Issue by ajtribick** [aldanor/hdf5-rust#201]
I have an HDF5 dataset consisting of a 1D array of compound types, produced by astropy on a table with a `MaskedColumn`. The field name for the mask is "foo.mask", which does not seem to play nice with the derive macro. It would be useful to support something like:

```rust
#[derive(H5Type, Debug)]
#[repr(C)]
struct MyRow {
    foo: f64,
    #[hdf5(name = "foo.mask")]
    foo_mask: bool,
}

// ...

let array = dataset.read_1d::<MyRow>()?;
```

Apologies if this kind of thing is already supported and I didn't manage to find the right place in the documentation.

**Comment by mulimoen** [comment]
That is a great idea! The trick is to modify the `derive` macro slighly by adding a helper attribute:
```rust
#[proc_macro_derive(H5Type, attributes(hdf5))]
pub fn derive(...)
```
Then one has to `pluck` the fields of `Fields::Unnamed` and extract the name attribute. I'd be happy to mentor if you wish to implement this.

**Comment by aldanor** [comment]
We should probably follow the [serde convention](https://serde.rs/field-attrs.html) then, and call it `#[hdf5(rename = "...")]`?
