### ISSUE TITLE
inflateInit() error with static + hdf5-rust 0.8

### ISSUE THREAD

**Issue by gauteh** [aldanor/hdf5-rust#206]
Hi,

When I tried to upgrade to latest hdf5-rust one of my tests starated failing when trying to read the attached dataset.
[chunked_gzipped.zip](https://github.com/aldanor/hdf5-rust/files/8331936/chunked_gzipped.zip)

```
        let h = hdf5::File::open(i.path().unwrap()).unwrap();
        let hvs = h
            .dataset("d_4_gzipped_chunks")
            .unwrap()
            .read_raw::<f32>()
            .unwrap();
``` 

```
---- reader::cache::tests::read_chunked_gzipped_2d stdout ----
thread 'reader::cache::tests::read_chunked_gzipped_2d' panicked at 'called `Result::unwrap()` on an `Err` value: H5Dread(): can't read data: inflateInit() failed', src/reader/cache.rs:186:14
```

https://github.com/gauteh/hidefix/blob/hdf5-08/src/reader/cache.rs#L183

Regards, Gaute

**Comment by mulimoen** [comment]
Are you using the static build without `hdf5-sys/zlib`? The automatic enablement of this feature is still waiting for a MSRV bump for weak dependency features

**Comment by gauteh** [comment]
No, I am using with `hdf5-sys/zlib`.

**Comment by mulimoen** [comment]
I can't reproduce on ubuntu 18.04 with system hdf5 (1.10.0) or on my Arch aarch64 with hdf5 1.12.1. What is your platform?

**Comment by gauteh** [comment]
Do you have the chance to try and run `cargo test` on this PR: https://github.com/gauteh/hidefix/pull/6 ? Ubuntu 18.04, sys-hdf5 1.10. But this is using the `static` feature.

**Comment by mulimoen** [comment]
I can reproduce the error, it seem something goes wrong when `zlib` is built statically. The error code from `inflateInit` is -2, `Z_STREAM_ERROR`. From `zlib.h`:

> inflateInit returns Z_OK if success, ..., or Z_STREAM_ERROR if the parameters are invalid, such as a null pointer to the structure.

**Comment by mulimoen** [comment]
And things work if one specifies the "zlib-ng" feature of "libz-sys"

**Comment by gauteh** [comment]
Is it possible for me to set that feature as a user of hdf5?

**Comment by mulimoen** [comment]
Yes, you can include
```toml
libz-sys = { version = "1", features = ["zlib-ng"], default-features = false }
```
as a dependency. Since features coalesce, this should be used when building hdf5

**Comment by gauteh** [comment]
Thanks, that solves it.

**Comment by mulimoen** [comment]
The error caused by this line: https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/inflate.c#L209, `Z_SOLO` is only set on [`!cfg!(feature = "libc") || target.starts_with("wasm32")`](https://github.com/rust-lang/libz-sys/blob/main/build.rs#L118), so either you specify `libc` as a feature (https://github.com/rust-lang/libz-sys/blob/main/Cargo.toml#L20), or you can use `zlib-ng` as a workaround. A fix would be either making `hdf5` set an allocator, or that `hdf5-src` sets the `libc` feature, which we need to include anyway.
