### ISSUE TITLE
Support both hdf5-1.14 and Ubuntu-latest.

### ISSUE THREAD

**Issue by hyoklee** [aldanor/hdf5-rust#230]
Please update GitHub Action (e.g., `apt:` section).

**Comment by mulimoen** [comment]
I don't see hdf 1.14 being packaged in ubuntu. Hdf 1.14 will be supported once #227 is merged

**Comment by hyoklee** [comment]
@mulimoen, thank you for your reply. 
Yes, Ubuntu package is not available yet.
I created this issue in advance as a reminder.

**Comment by Berrysoft** [comment]
When will #227 be merged? #229 needs it.

**Comment by kiranshila** [comment]
Arch Linux's official package for HDF5 was updated on the 25th (https://archlinux.org/packages/community/x86_64/hdf5/), so there's probably a good chunk of people (myself included) who would love to see this merged.
