### ISSUE TITLE
Dataset::name() is very slow and gets slower

### ISSUE THREAD

**Issue by tobias-roehmel** [aldanor/hdf5-rust#234]
Hi,

Thanks for the library, very nice work!

I have an issue though. I have existing hdf5 files where the name of the datasets is a timestamp of the data.
I want to convert the hdf5 file to CSV and need this timestamp for every dataset. But reading the dataset name
for every dataset in my file is very slow. I have some example code that also exhibits this behavior:
```
fn main() {
    let h5_path = "test.h5";
    use hdf5::File;
    let file = File::open(h5_path).unwrap();
    let datasets: Vec<hdf5::Dataset> = file.group("/TEMP_DATA").unwrap().datasets().unwrap();

    for dataset in datasets {
        let start = Instant::now();
        let name = dataset.name();
        let duration = start.elapsed();
        println!("{name} {:?}", duration);
    }
}
``` 
In this example, the duration gets bigger and bigger.
I assume that this is an issue with this library because this works in Python which I think is also a wrapper around the hdf5 library:
```
import h5py

filename = "test.h5"
with h5py.File(filename, 'r') as f:
    datasets = f["/TEMP_DATA"]
    for dataset in datasets:
        print(dataset)
```
This prints everything in under a second while the Rust code takes minutes.

Am I doing something wrong or is there an issue here?

Best regards,
Tobias

**Comment by tobias-roehmel** [comment]
Hi mulimoen,
thanks for your reply. I uploaded a test file here [https://filetransfer.io/data-package/W4Qj8yLi#link](https://filetransfer.io/data-package/W4Qj8yLi#link). I hope this works. My rust hdf5 version is 0.8.1 and I have libhdf5_serial.so.103.3.0 installed. Is that what you need?

**Comment by tobias-roehmel** [comment]
I also need to open the dataset because I'm doing a calculation on it. But opening it and doing the calculation is faster than reading the names. But I'll try to read the names separately with member_names and see if that works. Thanks!

**Comment by mulimoen** [comment]
I think it is just the `name` function which is slow, reading the shape off each dataset (opening dataset in the loop) is as fast as in h5py
