### ISSUE TITLE
Support for v1.14.0

### ISSUE THREAD

**Issue by kdheepak** [aldanor/hdf5-rust#239]
Hi,

Thanks for maintain the HDF5 rust package!

Would it be possible to support v1.14.0? It might be naive to assume this but I believe just this line would need to be modified, right?

https://github.com/aldanor/hdf5-rust/blob/5e5bedbf29ef45f2ae90b99375a0dc97cc3df408/hdf5-sys/build.rs#L32

**Comment by mulimoen** [comment]
See #227 for this

**Comment by kdheepak** [comment]
Thanks!
