### ISSUE TITLE
Invalid H5_VERSION: "1.14.1-2"

### ISSUE THREAD

**Issue by hombit** [aldanor/hdf5-rust#248]
I have hdf5 installed from homebrew, and it has this version tag in `H5pubconf.h`: `H5_VERSION: "1.14.1-2"`. It looks like it is currently not recognized by `hdf5-rust`

**Comment by mulimoen** [comment]
Is this with `hdf5-sys` from `master`? This should have been fixed by #227 and we do run CI on a [similar install](https://github.com/aldanor/hdf5-rust/blob/26046fb4900ec38afd2a1c0494cff688b288662e/.github/workflows/ci.yml#L60).

**Comment by hombit** [comment]
I can build `hdf5-sys` from `master`! I'm sorry for the noise and I hope you release it soon.
