### ISSUE TITLE
VS Code can't find HDF5 installation

### ISSUE THREAD

**Issue by themathsgirl** [aldanor/hdf5-rust#252]
I am using  hdf5 = "0.8.1" in my Cargo.toml in VS Code.

I went to the [HDF5 website](https://www.hdfgroup.org/downloads/hdf5/), downloaded hdf5-1.14.1-2-Std-win10_64-vs17.zip and hdf5-1.14.1-2-Std-win10_64-vs16.zip, and ran the installers to install HDF5.

I then restarted my PC for good measure.

However when I cargo build or cargo run my code, I get an error saying it can't finding any installations of HDF5, despite the fact I do have installations:
  ```
 Compiling hdf5-sys v0.8.1
error: failed to run custom build command for `hdf5-sys v0.8.1`

Caused by:
  process didn't exit successfully: `blahblahblah` (exit code: 101)
  --- stdout
  Searching for installed HDF5 (any version)...
  Found no HDF5 installations.

  --- stderr
  thread 'main' panicked at 'Unable to locate HDF5 root directory and/or headers.', blahblahblah
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(the blahblahblah is the file path)

How do I make hdf5 Rust in VS Code find the installations?

**Comment by riyueniao** [comment]
@themathsgirl Hi, I am in the same situation as you, how do you fix that?

**Comment by themathsgirl** [comment]
I didn't - I ended up converting the HDF5 data into CSV (via h5py) and then ran my Rust code on the CSV data.
