### ISSUE TITLE
Lack of documentation on thread safety

### ISSUE THREAD

**Issue by OWissett** [aldanor/hdf5-rust#255]
Can someone point me towards the docs which explain/give examples of how to use HDF5-rust with multithreading?

**Comment by OWissett** [comment]
Since the README states that it should be threadsafe, however, I am getting an issue with open the same file in two threads. I am guessing it might not be safe in the sense that it can open the same file twice?

**Comment by mulimoen** [comment]
The library is thread-safe in that it all calls are serialized since `hdf5` is not thread-safe. So reading from two threads will not work in parallel. What kind of error do you see on opening the same file twice?

**Comment by OWissett** [comment]
I probably misunderstood, I was trying to open the same file at once in two threads.

**Comment by mulimoen** [comment]
The library should support it, so if you get weird errors it would be great to have a look and get to the bottom of it
