### ISSUE TITLE
If you specify the offline path of the ndarray crate in cargo.toml, the example code cannot be compiled.

### ISSUE THREAD

**Issue by SilmaliTech** [aldanor/hdf5-rust#263]
I tried combining many different versions of ndarray and hdf5 crates, but they all failed. The problem occurs when you try to use the ndarray crate offline.
I tried them one by one while looking at the dependencies in crate.io. The result is all failure...
# sequence of the work.
1. cargo new aaaaaa -bin
2. Define dependencies in cargo.toml
```rust
ndarray = { version = "0.15.6"}
hdf5 = { version = "0.8.1" }
# There are no problems compiling the example code.
```
3. Download ndarray 0.15.6 version from github and move to the project folder!
```rust
ndarray = { path = "ext_library/ndarray-0.15.6", version = "0.15.6"}
hdf5 = { version = "0.8.1" }
# Compilation of example code is not possible.
```
# Error that occurs
## 1
the trait bound `ndarray::ArrayBase<OwnedRepr<Pixel>, ndarray::Dim<[usize; 2]>>: AsRef<[_]>` is not satisfied
required for `ndarray::ArrayBase<ndarray::ViewRepr<&_>, ndarray::dimension::dim::Dim<[usize; 1]>>` to implement `From<&ndarray::ArrayBase<OwnedRepr<Pixel>, ndarray::Dim<[usize; 2]>>>`
required for `&ndarray::ArrayBase<OwnedRepr<Pixel>, ndarray::Dim<[usize; 2]>>` to implement `Into<ndarray::ArrayBase<ndarray::ViewRepr<&_>, ndarray::dimension::dim::Dim<[usize; 1]>>>`
## 2
can't compare `ndarray::ArrayBase<ndarray::data_repr::OwnedRepr<Pixel>, _>` with `ndarray::ArrayBase<OwnedRepr<Pixel>, ndarray::Dim<[usize; 2]>>`
the trait `PartialEq<ndarray::ArrayBase<OwnedRepr<Pixel>, ndarray::Dim<[usize; 2]>>>` is not implemented for `ndarray::ArrayBase<ndarray::data_repr::OwnedRepr<Pixel>, _>`
the following other types implement trait `PartialEq<Rhs>`:
  <ndarray::ArrayBase<S, D> as PartialEq<ndarray::ArrayBase<S2, D>>>
  <ndarray::ArrayBase<S, D> as PartialEq<&'a ndarray::ArrayBase<S2, D>>>
  <&'a ndarray::ArrayBase<S, D> as PartialEq<ndarray::ArrayBase<S2, D>>>
## 3
the trait bound `Selection: From<SliceInfo<[SliceInfoElem; 2], ndarray::Dim<[usize; 2]>, ndarray::Dim<[usize; 2]>>>` is not satisfied
the following other types implement trait `From<T>`:
  <Selection as From<usize>>
  <Selection as From<ndarray::ArrayBase<ndarray::data_repr::OwnedRepr<usize>, ndarray::dimension::dim::Dim<[usize; 1]>>>>
  <Selection as From<ndarray::ArrayBase<ndarray::data_repr::OwnedRepr<usize>, ndarray::dimension::dim::Dim<[usize; 2]>>>>
  <Selection as From<ndarray::ArrayBase<ndarray::ViewRepr<&usize>, ndarray::dimension::dim::Dim<[usize; 2]>>>>
  <Selection as From<ndarray::ArrayBase<ndarray::ViewRepr<&usize>, ndarray::dimension::dim::Dim<[usize; 1]>>>>
  <Selection as From<SliceOrIndex>>
  <Selection as From<_IMPL_H5TYPE_FOR_Color::_h5::Hyperslab>>
  <Selection as From<Vec<usize>>>
and 25 others
required for `SliceInfo<[SliceInfoElem; 2], ndarray::Dim<[usize; 2]>, ndarray::Dim<[usize; 2]>>` to implement `Into<Selection>`
required for `Selection` to implement `TryFrom<SliceInfo<[SliceInfoElem; 2], ndarray::Dim<[usize; 2]>, ndarray::Dim<[usize; 2]>>>`

**Comment by mulimoen** [comment]
You might find the information you are looking for here: https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html

That should override `ndarray` in all dependencies

**Comment by mulimoen** [comment]
No problem, feel free to post a new question if there is something specific you are trying to do with this crate
