### ISSUE TITLE
Static builds fails on Windows

### ISSUE THREAD

**Issue by SteffenSunde** [aldanor/hdf5-rust#280]
Hi,

Trying to compile statically with HDF5 fails on windows (VS17, rust 1.77.2). Found some useful discussions in here but still have problems. 

- Installed HDF5 1.14.3 (also tried versions 1.10.11 and 1.12.3)
- Added to Cargo.toml:
```toml
hdf5 = { git = "https://github.com/aldanor/hdf5-rust.git" }
hdf5-sys = { git = "https://github.com/aldanor/hdf5-rust.git", features = ["static"]}
```
- Set `HDF5_DIR` environment variable to `C:\Program Files\HDF_Group\HDF5\1.14.3`
- `cargo build` cause 262 errors like the following
```error
error[E0308]: mismatched types
   --> C:\Users\heyjoe\.cargo\git\checkouts\hdf5-rust-c1072d7a2617f7d8\694e900\hdf5\src\globals.rs:44:68
    |
44  |         pub static $rust_name: H5GlobalConstant = H5GlobalConstant($c_name);
    |                                                   ---------------- ^^^^^^^ expected `&usize`, found `&i64`
    |                                                   |
    |                                                   arguments to this struct are incorrect
...
322 | link_hid!(H5E_BADSIZE, h5e::H5E_BADSIZE);
    | ---------------------------------------- in this macro invocation
    |
    = note: expected reference `&'static usize`
               found reference `&'static i64`
note: tuple struct defined here
   --> C:\Users\heyjoe\.cargo\git\checkouts\hdf5-rust-c1072d7a2617f7d8\694e900\hdf5\src\globals.rs:19:12
    |
19  | pub struct H5GlobalConstant(
    |            ^^^^^^^^^^^^^^^^
    = note: this error originates in the macro `link_hid` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `hdf5` (lib) due to 262 previous errors
```

Hope get some help with this. Thank you very much!

**Comment by mulimoen** [comment]
It is likely the wrong path triggers in https://github.com/aldanor/hdf5-rust/blob/694e900972fbf5ffbdd1a2294f57a2cc3a91c994/hdf5/src/globals.rs#L19 causing the build error. I don't think the build script is clever enough to choose the right library to link and tries the wrong one.

The `static` feature of `hdf5-sys` should compile hdf5 from scratch, so you should not need to set `HDF5_DIR` (or compile the library yourself).

**Comment by SteffenSunde** [comment]
You're right! Removing the environment variable and rebooting solved the issue. Thank you very much!
