### ISSUE TITLE
Compound Type

### ISSUE THREAD

**Issue by mpiannucci** [aldanor/hdf5-rust#281]
How can i read values from a dataset with a compound data type? The type is recognized by I cannot find the way that the data values can actually be extracted. 

thanks for any help!

**Comment by mulimoen** [comment]
You can see the `read` methods on [`Container`]( https://docs.rs/hdf5/latest/hdf5/struct.Container.html). Check also out the [example in the readme](https://github.com/aldanor/hdf5-rust?tab=readme-ov-file#example).
