### ISSUE TITLE
Fix Wine CI Runner

### ISSUE THREAD

**Issue by JamesMc86** [aldanor/hdf5-rust#286]
Not got time to look at this now but thought I would share my notes.

I noticed the Wine runner is now broken. This is related to Rust 1.76 dropping support for Windows 7 and now requires the bcryptprimitives.dll.

From research, this was added in Wine 8.13, but the version in the Ubuntu repos is much older, so the CI system would need to install Wine from a newer repo, like adding the Wine repos.

**Comment by mulimoen** [comment]
I suppose pinning to rust `1.75` is a pragmatic fix?
