### ISSUE TITLE
How to write/read ndarray?

### ISSUE THREAD

**Issue by DenTyur** [aldanor/hdf5-rust#298]
Hi there!

I am trying to write (or read) a 3D ndarray into an hdf5 file, but all my attempts fail. I would be immensely grateful if someone would give me an example of how to do this!

**Comment by mulimoen** [comment]
There is an example here you could extend for your case: https://github.com/aldanor/hdf5-rust/blob/master/hdf5/examples/chunking.rs

**Comment by DenTyur** [comment]
Thanks a lot
