### ISSUE TITLE
Example for writing and reading user block

### ISSUE THREAD

**Issue by SuperFluffy** [aldanor/hdf5-rust#41]
I would like to store some extra information about the data stored in my hdf5 file in the user block part of the file. I am not sure how to go about doing that. Can somebody maybe provide an example?

**Comment by aldanor** [comment]
The user block is just that - a section at the very beginning of the file that HDF5 won't touch.

You simply open the file as normal and read/write those bytes.

I don't think the official C/C++ API or wrappers like `h5py` provide any helpers to do that either, other than providing userblock size (which we also do)... 

You could, in theory, provide helpers in `File` for reading and writing the userblock, just need to be careful with the file being empty, non-existent, the handle already being open, especially when writing the userblock. There's so many edge cases here that it's typically just left to the user.

**Comment by SuperFluffy** [comment]
It turned out that serde was complaining about trailing characters when the serialized json was shorter than the userblock.

I thus opted to forego the userblock and just write my serialized json as a `&[u8]` to a dataset `/configuration`. The problem with the userblock was that I would need to safe the length of the serialized json at the beginning of the file, read that, and then pass it to serde's deserializer. This was in principle doable, but it was less of a hassle to do it with a dataset.

Alternatives would have been:

+ fill the remaining space in the userblock with explicit whitespace so that the we just pass the length of the userblock to serde and have it skip the whitespace;
+ use a different, probably not self-describing fileformat; this would have tied me too much to a specific implementation.

**Comment by aldanor** [comment]
@SuperFluffy Saving it to a scalar bytes dataset is generally a better thing to do. I've written JSON to HDF5 many-many times, including via serde - it works perfectly fine and is much less flaky than via the superblock (especially on NFS systems, it's easy to mess up your whole file by writing to superblock while having the handle open elsewhere), plus it's self-descriptive. Tbh I'm not sure why people would use superblock at all.
