### ISSUE TITLE
Compiling for WebAssembly

### ISSUE THREAD

**Issue by kerkomen** [aldanor/hdf5-rust#42]
Compiling hdf5-sys and hdf5-types for WebAssembly seems to fail.
While `cargo build` is successful, running `wasm-pack build` ends up in a bunch of similar errors about libc:

```
error[E0425]: cannot find function `malloc` in module `libc`
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/hdf5-types-0.5.1/src/array.rs:71:29
   |
71 |             let dst = libc::malloc(len * mem::size_of::<T>());
   |                             ^^^^^^ not found in `libc`
```

Is might be related to https://github.com/rust-lang/libc/issues/858 but that issue seems to be resolved.

It should be possible to reproduce the issue by adding hdf5 dependency to `Cargo.toml` 

```
[dependencies]
hdf5 = "0.5.1"
```

followed by running `wasm-pack build`.

**Comment by aldanor** [comment]
Is this still an issue? I guess this is more a question of compiling `hdf5-types`. In fact, we don't really care if it's `libc::malloc()` or anything else since we are responsible for deallocating it (and not HDF5). If you have an alternative suggestion for `hdf5-types` that would work with wasm - sure, shoot.

**Comment by aldanor** [comment]
@kerkomen Have you managed to compile the entire HDF5 C library into web assembly?...

**Comment by aldanor** [comment]
Closing since it’s unclear what the OP means

**Comment by shernshiou** [comment]
Yes @aldanor 

```
error[E0425]: cannot find function `malloc` in crate `libc`
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/hdf5-types-0.6.0/src/array.rs:71:29
   |
71 |             let dst = libc::malloc(len * mem::size_of::<T>());
   |                             ^^^^^^ not found in `libc`
```

```
[dependencies]
hdf5 = "0.6.0"
```

**Comment by anilbey** [comment]
How can I compile the HDF5 C Library into WASM?
