### ISSUE TITLE
h5lock is private

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [aldanor/hdf5-rust#60]
Like we discussed, I wrote my own attribute reader because it's still not supported. Everything went OK, until I tried to use `h5lock` to make my low-level calls sync with the library. That didn't work from the outside, and I got the error:
```
error[E0603]: module `sync` is private
 --> <::hdf5::macros::h5lock macros>:5:53
  |
5 | ] # [ allow ( unused_unsafe ) ] unsafe { $ crate :: sync :: sync ( || $ expr )
  |                                                     ^^^^
```
Can you please make `sync` it public?

**Comment by aldanor** [comment]
It's already done in my WIP summer branch :) (which is nearing completion, I'll push it in the current state tomorrow, but it will require a bit more work to finish).

```
commit 4cca17188c3707f76f4eef48e1a541c0c8e3c705
Author: Ivan Smirnov <i.s.smirnov@gmail.com>
Date:   Sun Jul 21 15:15:43 2019 +0100

    Allow using h5{check,lock!,try!,call!} externally
```

... and, as a matter of fact, in the next version after that I'm planning to get rid of all the macros `h5try!` etc, and instead using functions and `sync::sync` directly everywhere and make it all completely public (partially due to completions and code analysis not working in IDEs, but it'd be nice to get macro-free).

**Comment by TheQuantumPhysicist** [comment]
Great! Thanks! Hopefully there won't be any other conflicts with the code I used from you so far.

I'm sorry, I don't understand. Are you also gonna remove `h5lock`? That's the only macro I'm using for synchronization.

Btw, a macro has the benefit that it makes the code much shorter. For example, using a macro can also including `unsafe` blocks, which are used everywhere in HDF5 interfacing.

**Comment by aldanor** [comment]
> I'm sorry, I don't understand. Are you also gonna remove h5lock? That's the only macro I'm using for synchronization.

So the current

```rust
pub fn selection_size(&self) -> usize {
    h5call!(H5Sget_select_npoints(self.id())).ok().map_or(0, |x| x as _)
}
```

will probably look like this (maybe we can add versions that take unsafe closures, so that `unsafe` can be omitted though, since it's going to be all over the place...):

```rust
use hdf5::{sync, h5, h5s};
// sync() = just sync whatever you want, declare unsafe yourself
// h5() = the current "h5check()", converts HDF5 results into hdf5::Result<...>
// h5s() = same as h5(), but synchronized

pub fn selection_size(&self) -> usize {
    sync(|| unsafe { h5(H5Sget_select_npoints(id)) }).ok().map_or(0, |x| x as _)
}

// or

h5s(|| unsafe { H5Sget_select_npoints(id) })
```

Another option is to make `sync()` and `h5s()` take unsafe closures, but then I think they need to be unsafe themselves (so you'll end up writing `unsafe` somewhere, I think). It's more verbose but not that bad. Still need to think a bit about it.

> Btw, a macro has the benefit that it makes the code much shorter. For example, using a macro can also including unsafe blocks, which are used everywhere in HDF5 interfacing.

True.

**Comment by TheQuantumPhysicist** [comment]
I see. Actually I prefer the macros as they are now. I believe IDEs will have better support for all this in the future, and with macros it's already super-clean.

Even in C++, where I wrote this abstraction layer myself from scratch, I used a macro for the `lock_guard`. It's probably the natural way of doing things ;-)

**Comment by aldanor** [comment]
Yea - we can probably leave those macros as is, but I still was looking forward to make the core codebase mainly macros-less, when you have 10K+ lines of code, without proper IDE support things get pretty painful :/

Anyways, this will be up for discussion a bit later.

Just occured to me... there's actually yet another option - allowing `#[h5lock]` attribute on functions, making it unsafe and sync, so the above could hypothetically be

```rust
#[h5lock]
pub fn selection_size(&self) -> usize {
    h5(H5Sget_select_npoints(self.id())).ok().map_or(0, |x| x as _)
}

// or even...

#[h5lock]
pub fn selection_size(&self) -> usize {
    H5Sget_select_npoints(self.id()).h5().ok().map_or(0, |x| x as _)
}

```

That's ^ actually the way it's done in h5py.

Man, I love bikeshedding :D

**Comment by TheQuantumPhysicist** [comment]
This looks very cool. However, consider that some people may not want to write another abstraction layer for every HDF5 C function, because such an attribute will exercise a full lock over the whole function. But for those with a huge code base, this can be very useful ;-)

**Comment by TheQuantumPhysicist** [comment]
Hey, man. Is this ready to be merged to master?
