### ISSUE TITLE
Serde macro namespace clash for Windows builds

### ISSUE THREAD

**Issue by veeenu** [aldanor/hdf5-rust#62]
I am using both `serde` and `serde_derive` in my own crate which depends on `hdf5`. After adding the two dependencies to my crate, the following happens:

```
error[E0252]: the name `Deserialize` is defined multiple times
   --> lib\hdf5-rust\hdf5-sys\build.rs:345:9
    |
344 |     use serde::{Deserialize, Deserializer};
    |                 ----------- previous import of the macro `Deserialize` here
345 |     use serde_derive::Deserialize;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^ `Deserialize` reimported here
    |
    = note: `Deserialize` must be defined only once in the macro namespace of this module
```

This prevents me from successfully building the library, but the fix is rather easy:

```rust
use serde::{Deserialize, Deserializer};
use serde_derive::{Deserialize as SDDeserialize}; 
// [...]
#[derive(Clone, SDDeserialize)]
struct App {
```

I found [this issue](https://github.com/serde-rs/serde/issues/1441) which seems related.

**Comment by aldanor** [comment]
Thanks for reporting! Wonder what does Windows have to do with this at all though?

I'll see if I can reproduce it on macOS / Linux, will include the fix into the current dev branch if it's reproducible.

**Comment by veeenu** [comment]
I believe this can only be reproduced on Windows because the duplicate `use Deserialize` declaration is found under a `#[cfg(windows)]` block (specifically, [here](https://github.com/aldanor/hdf5-rust/blob/master/hdf5-sys/build.rs#L337)).

**Comment by jmrgibson** [comment]
PR here https://github.com/aldanor/hdf5-rust/pull/64
