### ISSUE TITLE
ndarray 0.13 support

### ISSUE THREAD

**Issue by windelbouwman** [aldanor/hdf5-rust#74]
Hi,

Thanks for creating this crate, it is fantastic!

Could the dependency on ndarray be relaxed so both 0.12 and 0.13 of this crate can be supported? Not a big issue, but it took me some time to figure out that I mixed ndarray crate versions in my application.

Regards,
Windel

**Comment by aldanor** [comment]
Just bumped the ndarray version to 0.13 if that's ok? If it turns out someone still needs 0.12 for whatever reason we can relax it back.

**Comment by windelbouwman** [comment]
Okay, thanks!
