### ISSUE TITLE
Make mod globals public?

### ISSUE THREAD

**Issue by kalcutter** [aldanor/hdf5-rust#80]
When using the hdf5-sys crate directly it would be convenient to have access to the safe-initialised globals from the hdf5 crate instead of having to reinvent that functionality. Currently we are patching the hdf5 crate for `pub mod globals`. Or is there a better way?

**Comment by aldanor** [comment]
Closed in #90

**Comment by aldanor** [comment]
@kalcutter Just out of wonder, what exactly did you need this for?

**Comment by kalcutter** [comment]
Thanks for making this change. The main reason is we use `H5Dwrite_chunk` to stream pre-filtered data. We use `H5P_DATASET_CREATE` for creating a CPL so we can call `H5Pset_chunk`, `H5Pset_fill_value`, and `H5Pset_filter`. We also use `H5T_STD_U32LE` to specify that the data is little-endian (even on a big endian machine).

**Comment by aldanor** [comment]
@kalcutter Thanks for clarifying. I very much hope all of the above will be doable in high-level library api soon (fill values, filters, chunks are already doable, big/little endian doable too - all in the feature/dcpl branch). The only thing that we'll need to add is direct chunk writing but that's fairly trivial.

My target was (and still is) to eliminate the need for users to dig into C APIs completely (and it would've been done already if it wasn't for the lack of developers in this crate who severely lack free time). I'll let you know when it's ready :)
