### ISSUE TITLE
Rust (ndarray) -> HDF5 -> Python (NumPy)?

### ISSUE THREAD

**Issue by bzm3r** [aldanor/hdf5-rust#83]
Suppose I have some `ndarray` matrices/vectors which I store in an HDF5 database using the `hdf5` crate.

Am I correct in understanding that if I open this database using Python's `h5py`, I can load the data into NumPy matrices, because HDF5's data representation is independent of `ndarray` and NumPy?

**Comment by aldanor** [comment]
That's kind of the whole point, yes.
