### ISSUE TITLE
support hdf5 v1.12

### ISSUE THREAD

**Issue by j4cko** [aldanor/hdf5-rust#94]
Building against hdf5 1.12 fails because Version::parse regards `H5_VERSION 1.12.0` as invalid. Are there any breaking changes that prevent this crate from being used with 1.12?

**Comment by mulimoen** [comment]
Arch linux recently upgraded hdf5 to version 1.12, so this breaks builds on this platform

**Comment by bazhenov** [comment]
Any news on this PR? Just bumped in this issue on Manjaro.
