### ISSUE TITLE
Deserialize dataset containing struct of Vec?

### ISSUE THREAD

**Issue by romainreignier** [aldanor/hdf5-rust#96]
HI! Thanks for your job on this nice crate to use HDF5 in Rust!

I want to read some HDF5 files in which a dataset contains this kind of data:

```Rust
struct LidarData {
    stamp: i64,
    number_of_layers: i32,
    layers: Vec<LidarLayer>
}

struct LidarLayer {
    number_of_scans_in_layer: i32,
    scans: Vec<LidarScan>
}

struct LidarScan {
    angle: f32,
    distance: f32,
}
```
So the memory has this layout:
![LidarMemoryLayout](https://user-images.githubusercontent.com/8845664/81415661-04f49780-9149-11ea-8fdd-687994ac4d6f.png)

Is there a nice way to deserialize it with `serde` or do I have to read all the dataset as a `Vec<u8>` and then manually parse the binary blob (as I would have done in C++).

I am quite new to Rust so any pointers would be much appreciated.

Thanks in advance.

**Comment by magnusuMET** [comment]
You can get up to LidarLayer with the `H5Type ` derive and changing types:
```rust
struct LidarData {
    stamp: i64,
    number_of_layers: i32,
    layers: Vec<LidarLayer>
}

#[repr(C)]
#[derive(Clone)]
#[derive(hdf5::H5Type)]
struct LidarLayer {
    number_of_scans_in_layer: i32,
    scans: hdf5::types::VarLenArray<LidarScan>,
}

#[repr(C)]
#[derive(Copy, Clone)]
#[derive(hdf5::H5Type)]
struct LidarScan {
    angle: f32,
    distance: f32,
}
```

Unfortunately `VarLenArray` requires the `Copy` trait, so we can't wrap `LidarLayer` using this.

**Comment by romainreignier** [comment]
Hi @magnusuMET 
Thank you for your help.
Actually, I think that I should read all the dataset in `Vec<u8>` and then iterate on it in a loop, isn't it?
Do you know something like a [QDataDteam](https://doc.qt.io/qt-5/qdatastream.html) in Rust that allows to read a `f64` from a `Vec<u8>`?

**Comment by magnusuMET** [comment]
Is the dataset delivered as one blob of binary data?

**Comment by romainreignier** [comment]
Actually, in my dataset the number of layers is always 1 so I can simplify the struct like that:

```Rust
#[repr(C)]
#[derive(Clone)]
#[derive(hdf5::H5Type)]
struct LidarData {
    stamp: i64,
    number_of_layers: i32,
    number_of_scans_in_layer: i32,
    scans: hdf5::types::VarLenArray<LidarScan>,
}

#[repr(C)]
#[derive(Copy, Clone)]
#[derive(hdf5::H5Type)]
struct LidarScan {
    angle: f32,
    distance: f32,
}

fn main() {
    let file = hdf5::File::open("data.h5").unwrap();
    let lidar_dataset_path = "Lidar/Data";
    let lidar_dataset = file.dataset(lidar_dataset_path).unwrap();
    let lidar_data = lidar_dataset.read_raw::<LidarData>().unwrap();
}
```

But then when I try to read, I have the error:
```
no conversion paths found
```

Maybe, this is because the data is chunked?

Here is hdfview infos on the dataset:
![image](https://user-images.githubusercontent.com/8845664/81426587-b26fa700-9159-11ea-9a95-c95a9a90005d.png)

**Comment by romainreignier** [comment]
Yes, it seems to be a binary blob, this is hdfview visualization of the data:
![image](https://user-images.githubusercontent.com/8845664/81426771-f367bb80-9159-11ea-87d0-fb5c177534ff.png)

**Comment by magnusuMET** [comment]
A byte parser with [Nom](https://crates.io/crates/nom) would look something like the following (assuming little endian):
```rust
use nom::{
    combinator::map,
    multi::many_m_n,
    number::complete::{le_f32, le_i32, le_i64},
    sequence::tuple,
    IResult,
};

struct LidarData {
    stamp: i64,
    number_of_layers: i32,
    layers: Vec<LidarLayer>,
}

#[derive(Clone)]
struct LidarLayer {
    number_of_scans_in_layer: i32,
    scans: Vec<LidarScan>,
}

#[derive(Copy, Clone)]
struct LidarScan {
    angle: f32,
    distance: f32,
}

fn parse(s: &[u8]) -> LidarData {
    lidar_data(s).unwrap().1
}

fn lidar_data(s: &[u8]) -> IResult<&[u8], LidarData> {
    use std::convert::TryInto;
    let (s, stamp) = le_i64(s)?;
    let (s, number_of_layers) = le_i32(s)?;
    let num_layers = number_of_layers.try_into().unwrap();
    let (s, layers) = many_m_n(num_layers, num_layers, lidar_layer)(s)?;

    Ok((
        s,
        LidarData {
            stamp,
            number_of_layers,
            layers,
        },
    ))
}

fn lidar_layer(s: &[u8]) -> IResult<&[u8], LidarLayer> {
    use std::convert::TryInto;
    let (s, number_of_scans_in_layer) = le_i32(s)?;
    let num_scans = number_of_scans_in_layer.try_into().unwrap();
    let (s, scans) = many_m_n(num_scans, num_scans, lidar_scan)(s)?;

    Ok((
        s,
        LidarLayer {
            number_of_scans_in_layer,
            scans,
        },
    ))
}

fn lidar_scan(s: &[u8]) -> IResult<&[u8], LidarScan> {
    map(tuple((le_f32, le_f32)), |(angle, distance)| LidarScan {
        angle,
        distance,
    })(s)
}

fn main() {}
```

**Comment by romainreignier** [comment]
@magnusuMET Oh! Thanks a lot for all this code!
I will try it out.
During my research, I found Nom but it seemed difficult to so how to code such a parser.

**Comment by romainreignier** [comment]
Great!
With a main implemented like that, it works to read the first `LidarData`:
```Rust
fn main()
{
    let file = hdf5::File::open("data.h5").unwrap();
    let lidar_dataset_path = "Lidar/Data";
    let lidar_dataset = file.dataset(lidar_dataset_path).unwrap();
    let lidar_raw = lidar_dataset.read_raw::<u8>().unwrap();
    let lidar_data = parse(&lidar_raw);
    println!("{:?}", lidar_data);
}
```
Now I have to find how to iterate to fill a `Vec<LidarData>` until all the dataset is read.
If you have any idea?
Maybe using the [`as_reader()`](https://aldanor.github.io/hdf5-rust/hdf5 /struct.Dataset.html#method.as_reader) I can get a `EOF` at the end?

**Comment by magnusuMET** [comment]
If you have the entire dataset in memory you could change the parser to:
```rust
fn parse(s: &[u8]) -> Vec<LidarData> {
    nom::multi::many0(lidar_data)(s).unwrap().1
}
```

**Comment by romainreignier** [comment]
Oh! Great! Thanks!
Nom seems to be really powerful but the syntax is quite unusual for me.
Thanks a lot!

And just to know, if all the dataset is not in memory, what would be the approach? Using the `streaming` API of Nom instead of the `complele`?

**Comment by magnusuMET** [comment]
Parser combinatorics are a bit of an odd concept, but provides very powerful abstractions!

I am honestly not sure what would be the best approach, I haven't played around with that situation. Changing to streaming would probably be a first step, and then some wrapper for reading more bytes until you have enough for a complete LidarData.

**Comment by romainreignier** [comment]
Hum ok, I see.
Anyway, for my use case, it is ok to load all the data in memory.
Thanks a lot for the help, it's amazing!

**Comment by magnusuMET** [comment]
No problem, happy to help!
