### ISSUE TITLE
How to append values to a dataset?

### ISSUE THREAD

**Issue by YoshieraHuang** [aldanor/hdf5-rust#97]
I use HDF5 to persist my large time-series data. I want to write my data asynchronously while receiving. Could you tell me how to create a dataset which maxlength is infinite and to append data to the end of this dataset?

**Comment by magnusuMET** [comment]
You can use the [resizable](https://aldanor.github.io/hdf5-rust/hdf5/struct.DatasetBuilder.html#method.resizable) function when declaring your variable.

**Comment by aldanor** [comment]
As @magnusuMET said, you can declare it as resizable (you can also write slices and not overwrite the whole dataset if needed).

**Comment by pkptzx** [comment]
@YoshieraHuang 
Who can give me an example ?
 append struct

tks
