### ISSUE TITLE
error with "hdf5-sys v0.6.1" when i run the example code

### ISSUE THREAD

**Issue by songroom2016** [aldanor/hdf5-rust#99]
#D:\time_test>cargo run --release
   Compiling hdf5-sys v0.6.1
error: failed to run custom build command for `hdf5-sys v0.6.1`

Caused by:
  process didn't exit successfully: `D:\time_test\target\release\build\hdf5-sys-0c82dab37fabc7d4\build-script-build` (exit code: 101)
--- stdout
Searching for installed HDF5 (any version)...
Found no HDF5 installations.

--- stderr
thread 'main' panicked at 'Unable to locate HDF5 root directory and/or headers.', C:\Users\songroom\.cargo\registry\src\github.com-1ecc6299db9ec823\hdf5-sys-0.6.1\build.rs:523:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

thanks!

**Comment by aldanor** [comment]
@songroom2016 Where is your HDF5 installed on this Windows machine?

**Comment by aldanor** [comment]
Closing since no response from OP, if details are provided we can reopen this.
